-- Migration 0001_init
-- Generated: 2026-06-28T14:12:13.591Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_config_values" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "value" text,
  "user_id" text
);
CREATE INDEX IF NOT EXISTS "read_config_values_tenant_id_idx" ON "read_config_values" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_config_values_unique" ON "read_config_values" ("key", "tenant_id", "user_id");

CREATE TABLE IF NOT EXISTS "read_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "starts_at" text NOT NULL,
  "location" text,
  "description" text,
  "guest_limit" integer
);
CREATE INDEX IF NOT EXISTS "read_events_tenant_id_idx" ON "read_events" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_rsvps" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "event_id" text NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "status" text DEFAULT 'yes',
  "plus_n" integer,
  "note" text
);
CREATE INDEX IF NOT EXISTS "read_rsvps_tenant_id_idx" ON "read_rsvps" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_invitations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "email" text NOT NULL,
  "role" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "invited_by" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_id_idx" ON "read_tenant_invitations" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique" ON "read_tenant_invitations" ("tenant_id", "email");

CREATE TABLE IF NOT EXISTS "read_tenant_memberships" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "roles" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_memberships_tenant_id_idx" ON "read_tenant_memberships" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_memberships_unique" ON "read_tenant_memberships" ("user_id", "tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenants" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "name" text NOT NULL,
  "is_enabled" boolean DEFAULT true NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenants_tenant_id_idx" ON "read_tenants" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenants_key_unique" ON "read_tenants" ("key");

CREATE TABLE IF NOT EXISTS "read_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "email" text NOT NULL,
  "password_hash" text,
  "display_name" text NOT NULL,
  "locale" text DEFAULT 'de',
  "last_active_tenant_id" text,
  "email_verified" boolean DEFAULT false NOT NULL,
  "roles" text DEFAULT '[]' NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "grace_period_end" timestamp with time zone,
  "pending_deletion_request_id" text
);
CREATE INDEX IF NOT EXISTS "read_users_tenant_id_idx" ON "read_users" ("tenant_id");
