-- Migration 0002_fix_starts_at_timestamp
-- Generated: 2026-07-04T09:08:36.822Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_events
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "read_events";
CREATE TABLE IF NOT EXISTS "read_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "starts_at" timestamp with time zone NOT NULL,
  "location" text,
  "description" text,
  "guest_limit" integer
);
CREATE INDEX IF NOT EXISTS "read_events_tenant_id_idx" ON "read_events" ("tenant_id");

-- read_tenant_invitations
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "read_tenant_invitations";
CREATE TABLE IF NOT EXISTS "read_tenant_invitations" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "role" text NOT NULL,
  "status" text DEFAULT 'pending' NOT NULL,
  "invited_by" text NOT NULL,
  "expires_at" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_id_idx" ON "read_tenant_invitations" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_email_bidx_idx" ON "read_tenant_invitations" ("email_bidx");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique" ON "read_tenant_invitations" ("tenant_id", "email");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_invitations_tenant_email_unique_bidx" ON "read_tenant_invitations" ("tenant_id", "email_bidx") WHERE "email_bidx" IS NOT NULL;

-- read_users
ALTER TABLE "read_users" ADD COLUMN "email_bidx" text;
CREATE INDEX IF NOT EXISTS "read_users_email_bidx_idx" ON "read_users" ("email_bidx");
