-- Migration 0005_read_tenants_0_129
-- Generated: 2026-07-07T20:56:07.851Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_tenants
ALTER TABLE "read_tenants" ADD COLUMN "status" text DEFAULT 'active' NOT NULL;
ALTER TABLE "read_tenants" ADD COLUMN "destroy_requested_at" timestamptz;
ALTER TABLE "read_tenants" ADD COLUMN "destroy_requested_by" text;
ALTER TABLE "read_tenants" ADD COLUMN "grace_period_end" timestamptz;
ALTER TABLE "read_tenants" ADD COLUMN "destroy_started_at" timestamptz;
ALTER TABLE "read_tenants" ADD COLUMN "destroyed_at" timestamptz;
