-- Migration 0006_text-blocks-for-legal
-- Generated: 2026-07-12T14:41:22.068Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_text_blocks" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "lang" text NOT NULL,
  "title" text NOT NULL,
  "body" text,
  "folder" text
);
CREATE INDEX IF NOT EXISTS "read_text_blocks_tenant_id_idx" ON "read_text_blocks" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_text_blocks_unique" ON "read_text_blocks" ("tenant_id", "slug", "lang");
