-- Migration 0007_billing-features
-- Generated: 2026-07-13T12:28:18.276Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_cap_counters" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "cap_name" text NOT NULL,
  "value" integer DEFAULT 0 NOT NULL,
  "period_start" timestamp with time zone NOT NULL,
  "last_soft_warned_at" timestamp with time zone
);
CREATE INDEX IF NOT EXISTS "read_cap_counters_tenant_id_idx" ON "read_cap_counters" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_subscriptions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "provider_name" text NOT NULL,
  "provider_customer_id" text NOT NULL,
  "provider_subscription_id" text NOT NULL,
  "status" text NOT NULL,
  "tier" text NOT NULL,
  "current_period_end" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_subscriptions_tenant_id_idx" ON "read_subscriptions" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_compliance_profiles" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "profile_key" text NOT NULL,
  "override" text
);
CREATE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_idx" ON "read_tenant_compliance_profiles" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_compliance_profiles_tenant_id_unique" ON "read_tenant_compliance_profiles" ("tenant_id");

CREATE TABLE IF NOT EXISTS "read_tenant_secrets" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "key" text NOT NULL,
  "envelope" jsonb NOT NULL,
  "kek_version" integer NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "last_rotated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "read_tenant_secrets_tenant_key_unique" ON "read_tenant_secrets" ("tenant_id", "key");

CREATE TABLE IF NOT EXISTS "read_tier_assignments" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "tier" text NOT NULL,
  "source" text
);
CREATE INDEX IF NOT EXISTS "read_tier_assignments_tenant_id_idx" ON "read_tier_assignments" ("tenant_id");
