-- Migration 0008_add-managed-pages
-- Generated: 2026-07-14T04:22:33.757Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_pages" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "lang" text NOT NULL,
  "title" text NOT NULL,
  "body" text,
  "description" text,
  "og_image" text,
  "published" boolean DEFAULT false NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_pages_tenant_id_idx" ON "read_pages" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_pages_unique" ON "read_pages" ("tenant_id", "slug", "lang");
