-- Migration 0011_framework-0154-bump
-- Generated: 2026-07-17T22:29:20.360Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_events
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "read_events";
CREATE TABLE IF NOT EXISTS "read_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "title" text NOT NULL,
  "slug" text NOT NULL,
  "starts_at" timestamp with time zone NOT NULL,
  "location" text,
  "description" text,
  "guest_limit" double precision
);
CREATE INDEX IF NOT EXISTS "read_events_tenant_id_idx" ON "read_events" ("tenant_id");

-- read_job_runs
-- WARN: column-type-change integer → double precision. Review USING-clause if needed.
ALTER TABLE "read_job_runs" ALTER COLUMN "duration" TYPE double precision;

-- read_rsvps
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
DROP TABLE IF EXISTS "read_rsvps";
CREATE TABLE IF NOT EXISTS "read_rsvps" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "event_id" text NOT NULL,
  "name" text NOT NULL,
  "email" text,
  "status" text DEFAULT 'yes',
  "plus_n" double precision,
  "note" text
);
CREATE INDEX IF NOT EXISTS "read_rsvps_tenant_id_idx" ON "read_rsvps" ("tenant_id");
