-- Migration 0012_store-table-rename
-- Generated: 2026-07-19T19:02:56.286Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_job_run_logs" (
  "id" serial PRIMARY KEY,
  "run_id" text NOT NULL,
  "level" text NOT NULL,
  "message" text NOT NULL,
  "timestamp" timestamp with time zone NOT NULL
);

-- === Changed tables ===
-- read_job_runs
-- WARN: column-type-change double precision → integer. Review USING-clause if needed.
ALTER TABLE "read_job_runs" ALTER COLUMN "duration" TYPE integer;

-- === Dropped tables ===
-- read_job_run_logs -> store_job_run_logs (kumiko-framework#1220). No ALTER
-- TABLE RENAME path exists (table identity is name-keyed), so this is
-- drop+create, not a rename. Job-run logs are an audit trail with no
-- retention requirement here.
DROP TABLE IF EXISTS "read_job_run_logs";
