-- Migration 0013_plusn-guestlimit-integer
-- Generated: 2026-07-22T08:42:20.666Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_events
-- Generator emitted DROP+CREATE+rebuild (managed-projection column-type
-- change). Hand-edited to a plain ALTER instead, mirroring money-horse#309's
-- read_share_tokens double->integer fix: guest_limit only ever holds whole
-- numbers, so no USING-clause/data loss risk, and this avoids a full
-- event-stream replay on deploy.
ALTER TABLE "read_events" ALTER COLUMN "guest_limit" TYPE integer;

-- read_rsvps
-- Generator emitted DROP+CREATE+rebuild (managed-projection column-type
-- change). Hand-edited to a plain ALTER instead, same rationale as above:
-- plus_n only ever holds whole numbers.
ALTER TABLE "read_rsvps" ALTER COLUMN "plus_n" TYPE integer;
