-- Migration 0014_add-user-sessions
-- Generated: 2026-07-27T17:03:56.059Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_user_sessions" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" text NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "user_id" text NOT NULL,
  "created_at" timestamp with time zone NOT NULL,
  "expires_at" timestamp with time zone NOT NULL,
  "revoked_at" timestamp with time zone,
  "ip" text,
  "user_agent" text
);
CREATE INDEX IF NOT EXISTS "store_user_sessions_tenant_id_idx" ON "store_user_sessions" ("tenant_id");
