-- Migration 0015_content-foundation-merge
-- Generated: 2026-08-02T09:21:41.816Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "read_template_resources" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "slug" text NOT NULL,
  "kind" text NOT NULL,
  "locale" text NOT NULL,
  "title" text,
  "folder" text,
  "content" text,
  "content_format" text NOT NULL,
  "variable_schema" text,
  "linked_resources" text,
  "scope" text NOT NULL,
  "parent_template_id" text,
  "status" text NOT NULL
);
CREATE INDEX IF NOT EXISTS "read_template_resources_tenant_id_idx" ON "read_template_resources" ("tenant_id");
CREATE UNIQUE INDEX IF NOT EXISTS "read_template_resources_unique" ON "read_template_resources" ("tenant_id", "slug", "kind", "locale");

-- === Changed tables ===
-- read_users
ALTER TABLE "read_users" ADD COLUMN "timezone" text;
ALTER TABLE "read_users" ALTER COLUMN "locale" DROP DEFAULT;

-- === Data migration: text-content -> template-resolver (show-pony#96) ===
-- read_text_blocks rows become kind='text-block' rows in
-- read_template_resources. New id/version/inserted_at per row (new
-- event-sourced aggregate — the old text-block event streams are not
-- migrated, see issue #96).
INSERT INTO "read_template_resources"
  ("tenant_id", "slug", "kind", "locale", "title", "folder", "content",
   "content_format", "variable_schema", "linked_resources", "scope",
   "parent_template_id", "status")
SELECT
  "tenant_id", "slug", 'text-block', "lang", "title", "folder", "body",
  'markdown', '{}', '{}',
  CASE WHEN "tenant_id" = '00000000-0000-4000-8000-000000000000' THEN 'system' ELSE 'tenant' END,
  NULL, 'active'
FROM "read_text_blocks";

-- === Dropped tables ===
-- read_text_blocks: superseded by read_template_resources (kind='text-block')
-- above, in the same migration as its data copy — no separate maintenance
-- window needed.
DROP TABLE IF EXISTS "read_text_blocks";
