-- Migration 0017_tenant-invitations-invited-by-bidx
-- Generated: 2026-08-13T17:27:22.881Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_tenant_invitations
ALTER TABLE "read_tenant_invitations" ADD COLUMN "invited_by_bidx" text;
CREATE INDEX IF NOT EXISTS "read_tenant_invitations_invited_by_bidx_idx" ON "read_tenant_invitations" ("invited_by_bidx");
