-- Migration 0019_fw-0210-schema
-- Generated: 2026-08-19T21:05:46.002Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_job_runs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "job_name" text NOT NULL,
  "bull_job_id" text NOT NULL,
  "status" text NOT NULL,
  "payload" text,
  "error" text,
  "attempt" integer DEFAULT 1 NOT NULL,
  "started_at" timestamp with time zone NOT NULL,
  "finished_at" timestamp with time zone,
  "duration" integer,
  "triggered_by_id" text
);
CREATE INDEX IF NOT EXISTS "store_job_runs_tenant_id_idx" ON "store_job_runs" ("tenant_id");

-- === Changed tables ===
-- read_users
ALTER TABLE "read_users" ADD COLUMN "display_name_bidx" text;
CREATE INDEX IF NOT EXISTS "read_users_display_name_bidx_idx" ON "read_users" ("display_name_bidx");

-- store_user_sessions
ALTER TABLE "store_user_sessions" ADD COLUMN "last_seen_at" timestamptz;

-- === Dropped tables ===
-- DESTRUCTIVE: DROP TABLE IF EXISTS "read_job_runs";  -- uncomment + ensure backup + run during maintenance window
