-- Migration 0020_rsvp_personal_self_search
-- Generated: 2026-08-23T06:59:38.751Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_rsvps
ALTER TABLE "read_rsvps" ADD COLUMN "name_bidx" text;
ALTER TABLE "read_rsvps" ADD COLUMN "email_bidx" text;
CREATE INDEX IF NOT EXISTS "read_rsvps_name_bidx_idx" ON "read_rsvps" ("name_bidx");
CREATE INDEX IF NOT EXISTS "read_rsvps_email_bidx_idx" ON "read_rsvps" ("email_bidx");
