-- Migration 0022_framework-0-220-bump
-- Generated: 2026-08-28T07:53:26.478Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_users
-- managed projection — recreated + rebuilt from events (see .rebuild.json)
-- WARN: destructive change (column type change: roles) forces DROP+CREATE + full event replay.
-- Consider an Expand/Contract split across two releases to avoid the rebuild — see docs/guides/expand-contract-managed-projections.md.
DROP TABLE IF EXISTS "read_users";
CREATE TABLE IF NOT EXISTS "read_users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id" uuid NOT NULL,
  "version" integer DEFAULT 1 NOT NULL,
  "inserted_at" timestamp with time zone DEFAULT now() NOT NULL,
  "modified_at" timestamp with time zone,
  "inserted_by_id" text,
  "modified_by_id" text,
  "is_deleted" boolean DEFAULT false NOT NULL,
  "deleted_at" timestamp with time zone,
  "deleted_by_id" text,
  "email" text NOT NULL,
  "email_bidx" text,
  "password_hash" text,
  "display_name" text NOT NULL,
  "display_name_bidx" text,
  "locale" text,
  "timezone" text,
  "last_active_tenant_id" text,
  "email_verified" boolean DEFAULT false NOT NULL,
  "roles" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "status" text DEFAULT 'active' NOT NULL,
  "grace_period_end" timestamp with time zone,
  "pending_deletion_request_id" text
);
CREATE INDEX IF NOT EXISTS "read_users_tenant_id_idx" ON "read_users" ("tenant_id");
CREATE INDEX IF NOT EXISTS "read_users_email_bidx_idx" ON "read_users" ("email_bidx");
CREATE INDEX IF NOT EXISTS "read_users_display_name_bidx_idx" ON "read_users" ("display_name_bidx");
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique" ON "read_users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique_bidx" ON "read_users" ("email_bidx") WHERE "email_bidx" IS NOT NULL;
