-- Migration 0023_fix-users-bidx-soft-delete-predicate
-- Generated: 2026-09-07T17:56:26.115Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_users
-- index "read_users_email_unique_bidx" changed (where "email_bidx" IS NOT NULL → "email_bidx" IS NOT NULL AND "is_deleted" = false) — recreated
DROP INDEX IF EXISTS "read_users_email_unique_bidx";
CREATE UNIQUE INDEX IF NOT EXISTS "read_users_email_unique_bidx" ON "read_users" ("email_bidx") WHERE "email_bidx" IS NOT NULL AND "is_deleted" = false;
