-- Migration 0025_framework-0-291-bump
-- Generated: 2026-09-19T20:31:09.279Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === New tables ===
CREATE TABLE IF NOT EXISTS "store_tenant_job_failures" (
  "id" serial PRIMARY KEY,
  "tenant_id" uuid NOT NULL,
  "job_name" text NOT NULL,
  "subject" text,
  "message_key" text NOT NULL,
  "failed_at" timestamp with time zone DEFAULT now() NOT NULL
);
