-- Migration 0026_framework-0-319-bump
-- Generated: 2026-09-27T05:02:00.345Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_subscriptions
ALTER TABLE "read_subscriptions" ADD COLUMN "cancel_at" timestamptz;
