-- Migration 0027_framework-0-330-bump
-- Generated: 2026-10-01T11:03:49.812Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- store_job_runs
CREATE INDEX IF NOT EXISTS "store_job_runs_started_at_idx" ON "store_job_runs" ("started_at");

-- store_user_sessions
CREATE INDEX IF NOT EXISTS "store_user_sessions_tenant_id_last_seen_at_idx" ON "store_user_sessions" ("tenant_id", "last_seen_at");
