-- Migration 0028_framework-0-343-bump
-- Generated: 2026-10-04T08:57:12.974Z
-- 
-- This file is generated by `kumiko migrate generate`. You may
-- hand-edit it before committing — add partial-indexes, BRIN-
-- variants, performance-tuning. After commit + apply, NEVER edit
-- this file again (production-DBs already ran it). Write a new
-- migration instead.

-- === Changed tables ===
-- read_tenant_invitations
ALTER TABLE "read_tenant_invitations" ADD COLUMN "global_roles" jsonb DEFAULT '[]'::jsonb NOT NULL;

-- === Retired framework tables ===
-- read_job_runs: retired since framework 0.210.0 — replaced by store_job_runs; the job run history was not migrated (operational data, not a system of record)
DROP TABLE IF EXISTS "read_job_runs";
